package dev.neko.app.ui

// Generated by tools/gen_cat_kt.py from tools/art/neko_cat.svg. Do not edit by hand.
/** One SVG path; a color of 0 means "not painted". Coordinates use the 400 x 440 art box. */
class CatShape(val d: String, val fill: Long, val stroke: Long, val width: Float)

object NekoArt {
    const val WIDTH = 400f
    const val HEIGHT = 440f
    val layers: Map<String, List<CatShape>> = mapOf(
        "shadow" to listOf(
            CatShape("M70 410 a130 14 0 1 0 260 0 a130 14 0 1 0 -260 0z", 0xFFF4A3A6L, 0L, 0f),
        ),
        "ears" to listOf(
            CatShape("M116 168 Q108 104 138 72 Q150 62 162 72 L206 116 Z", 0xFFFFFFFFL, 0xFF2B2B33L, 6f),
            CatShape("M134 112 Q138 92 150 84 L182 116 Z", 0xFFF4807FL, 0L, 0f),
            CatShape("M284 168 Q292 104 262 72 Q250 62 238 72 L194 116 Z", 0xFFFFFFFFL, 0xFF2B2B33L, 6f),
            CatShape("M266 112 Q262 92 250 84 L218 116 Z", 0xFFF4807FL, 0L, 0f),
        ),
        "body" to listOf(
            CatShape("M152 290 C120 310 98 350 100 385 C100 399 112 405 125 405 L275 405 C288 405 300 399 300 385 C302 350 280 310 248 290 Z", 0xFFFFFFFFL, 0xFF2B2B33L, 6f),
            CatShape("M96 372 a28 32 0 1 0 56 0 a28 32 0 1 0 -56 0z", 0xFFFFFFFFL, 0xFF2B2B33L, 6f),
            CatShape("M101 366 a15 20 0 1 0 30 0 a15 20 0 1 0 -30 0z", 0xFF2B2B33L, 0L, 0f),
            CatShape("M100 389 a12 11 0 1 0 24 0 a12 11 0 1 0 -24 0z", 0xFFF6A93BL, 0L, 0f),
            CatShape("M248 372 a28 32 0 1 0 56 0 a28 32 0 1 0 -56 0z", 0xFFFFFFFFL, 0xFF2B2B33L, 6f),
            CatShape("M269 366 a15 20 0 1 0 30 0 a15 20 0 1 0 -30 0z", 0xFF2B2B33L, 0L, 0f),
            CatShape("M276 389 a12 11 0 1 0 24 0 a12 11 0 1 0 -24 0z", 0xFFF6A93BL, 0L, 0f),
            CatShape("M116 399 a34 17 0 1 0 68 0 a34 17 0 1 0 -68 0z", 0xFFFFFFFFL, 0xFF2B2B33L, 6f),
            CatShape("M144 394 v11 M156 394 v11", 0L, 0xFF2B2B33L, 4f),
            CatShape("M216 399 a34 17 0 1 0 68 0 a34 17 0 1 0 -68 0z", 0xFFFFFFFFL, 0xFF2B2B33L, 6f),
            CatShape("M244 394 v11 M256 394 v11", 0L, 0xFF2B2B33L, 4f),
        ),
        "bib" to listOf(
            CatShape("M146 304 Q200 338 254 304 Q250 354 200 388 Q150 354 146 304Z", 0xFF6DD07AL, 0xFF2B2B33L, 5f),
            CatShape("M168 326 a10 10 0 0 1 20 0 M188 326 a10 10 0 0 1 20 0 M208 326 a10 10 0 0 1 20 0 M178 340 a10 10 0 0 1 20 0 M198 340 a10 10 0 0 1 20 0 M188 354 a10 10 0 0 1 20 0", 0L, 0xFFC4F5BFL, 3f),
        ),
        "collar" to listOf(
            CatShape("M152 286 Q200 314 248 286 L254 304 Q200 336 146 304 Z", 0xFFE5484DL, 0xFF2B2B33L, 5f),
            CatShape("M158 297 Q200 322 242 297", 0L, 0xFFF58C8FL, 3f),
        ),
        "bell" to listOf(
            CatShape("M181 330 a19 19 0 1 0 38 0 a19 19 0 1 0 -38 0z", 0xFFFFC93CL, 0xFF2B2B33L, 5f),
            CatShape("M183 335 H217", 0L, 0xFF2B2B33L, 4f),
            CatShape("M196.5 345 a3.5 3.5 0 1 0 7 0 a3.5 3.5 0 1 0 -7 0z", 0xFF2B2B33L, 0L, 0f),
            CatShape("M190 322 Q194 316 199 316", 0L, 0xFFFFF2B0L, 4f),
        ),
        "coin" to listOf(
            CatShape("M176 386 a30 40 0 1 0 60 0 a30 40 0 1 0 -60 0z", 0xFFFFC93CL, 0xFF2B2B33L, 6f),
            CatShape("M185 386 a21 30 0 1 0 42 0 a21 30 0 1 0 -42 0z", 0L, 0xFFE39A1BL, 3f),
            CatShape("M192 368 H220 M192 378 H220 M194 368 H205 Q218 368 218 379 Q218 390 205 390 H196 L216 410", 0L, 0xFF2B2B33L, 5f),
        ),
        "arm_left" to listOf(
            CatShape("M150 326 C132 342 134 368 156 386", 0L, 0xFF2B2B33L, 42f),
            CatShape("M150 326 C132 342 134 368 156 386", 0L, 0xFFFFFFFFL, 30f),
            CatShape("M146 392 a17 14 0 1 0 34 0 a17 14 0 1 0 -34 0z", 0xFFFFFFFFL, 0xFF2B2B33L, 5f),
            CatShape("M158 386 v8 M168 386 v8", 0L, 0xFF2B2B33L, 3.5f),
        ),
        "head" to listOf(
            CatShape("M98 212 C96 150 135 110 200 110 C265 110 304 150 302 212 C300 266 258 292 200 292 C142 292 100 266 98 212 Z", 0xFFFFFFFFL, 0xFF2B2B33L, 6f),
            CatShape("M168 114 Q200 104 234 114 Q224 142 200 140 Q176 140 168 114Z", 0xFF2B2B33L, 0L, 0f),
            CatShape("M214 108 Q240 112 250 126 Q238 148 214 143 Q224 126 214 108Z", 0xFFF6A93BL, 0L, 0f),
            CatShape("M164 152 L166 170 M178 148 L179 166 M236 152 L234 170 M222 148 L221 166", 0L, 0xFFF6B93BL, 5f),
            CatShape("M106 238 a26 18 0 1 0 52 0 a26 18 0 1 0 -52 0z", 0xFFF4707BL, 0L, 0f),
            CatShape("M242 238 a26 18 0 1 0 52 0 a26 18 0 1 0 -52 0z", 0xFFF4707BL, 0L, 0f),
            CatShape("M104 232 L138 237 M104 245 L138 244 M110 257 L138 251 M296 232 L262 237 M296 245 L262 244 M290 257 L262 251", 0L, 0xFF2B2B33L, 3f),
            CatShape("M191 221 Q200 214 209 221 Q205 230 200 231 Q195 230 191 221Z", 0xFF2B2B33L, 0L, 0f),
        ),
        "eyes_happy" to listOf(
            CatShape("M148 206 Q166 182 186 206 M214 206 Q234 182 252 206", 0L, 0xFF2B2B33L, 7f),
            CatShape("M148 206 L140 201 M252 206 L260 201", 0L, 0xFF2B2B33L, 4f),
        ),
        "eyes_open" to listOf(
            CatShape("M154 198 a13 15 0 1 0 26 0 a13 15 0 1 0 -26 0z M220 198 a13 15 0 1 0 26 0 a13 15 0 1 0 -26 0z", 0xFF2B2B33L, 0L, 0f),
            CatShape("M168 191 a4 4 0 1 0 8 0 a4 4 0 1 0 -8 0z M234 191 a4 4 0 1 0 8 0 a4 4 0 1 0 -8 0z", 0xFFFFFFFFL, 0L, 0f),
        ),
        "mouth_closed" to listOf(
            CatShape("M180 237 Q190 251 200 237 Q210 251 220 237", 0L, 0xFF2B2B33L, 5f),
        ),
        "mouth_open" to listOf(
            CatShape("M182 237 Q200 273 218 237 Q200 244 182 237Z", 0xFF7C2D3BL, 0xFF2B2B33L, 4f),
            CatShape("M192 255 Q200 266 208 255 Q200 249 192 255Z", 0xFFF58C93L, 0L, 0f),
        ),
        "paw_wave" to listOf(
            CatShape("M270 338 C312 332 324 286 318 238", 0L, 0xFF2B2B33L, 42f),
            CatShape("M270 338 C312 332 324 286 318 238", 0L, 0xFFFFFFFFL, 30f),
            CatShape("M288 212 a28 25 0 1 0 56 0 a28 25 0 1 0 -56 0z", 0xFFFFFFFFL, 0xFF2B2B33L, 6f),
            CatShape("M308 196 v12 M322 194 v12", 0L, 0xFF2B2B33L, 4f),
        ),
    )
}
