"""Generate app/.../ui/NekoArt.kt from tools/art/neko_cat.svg (paths only, grouped by <g id>)."""
import os
import xml.etree.ElementTree as ET

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
SRC = os.path.join(ROOT, 'tools', 'art', 'neko_cat.svg')
OUT = os.path.join(ROOT, 'app', 'src', 'main', 'kotlin', 'dev', 'neko', 'app', 'ui', 'NekoArt.kt')
NS = '{http://www.w3.org/2000/svg}'


def color(value: str | None) -> str:
    if not value or value == 'none':
        return '0L'
    return '0xFF' + value.lstrip('#').upper() + 'L'


def main() -> None:
    root = ET.parse(SRC).getroot()
    lines = [
        'package dev.neko.app.ui',
        '',
        '// Generated by tools/gen_cat_kt.py from tools/art/neko_cat.svg. Do not edit by hand.',
        '/** One SVG path; a color of 0 means "not painted". Coordinates use the 400 x 440 art box. */',
        'class CatShape(val d: String, val fill: Long, val stroke: Long, val width: Float)',
        '',
        'object NekoArt {',
        '    const val WIDTH = 400f',
        '    const val HEIGHT = 440f',
        '    val layers: Map<String, List<CatShape>> = mapOf(',
    ]
    for group in root.findall(NS + 'g'):
        shapes = []
        for path in group.findall(NS + 'path'):
            d = ' '.join(path.attrib['d'].split())
            shapes.append('CatShape("%s", %s, %s, %sf)' % (
                d, color(path.attrib.get('fill')), color(path.attrib.get('stroke')),
                path.attrib.get('stroke-width', '0')))
        lines.append('        "%s" to listOf(' % group.attrib['id'])
        lines += ['            ' + s + ',' for s in shapes]
        lines.append('        ),')
    lines += ['    )', '}', '']
    with open(OUT, 'w', encoding='utf-8', newline='\n') as f:
        f.write('\n'.join(lines))
    print('wrote', OUT)


main()
